mysql:
  username: ''
  password: ''
  host: localhost
  database: bukkit
  port: 3306
  prefix: ''
  savesPerDay: 64
BastionBlock:
  material: SPONGE
  #If squarefield is set to wrong, the field will be a circle
  squarefield: true
  effectRadius: 100
  includeYlevel: true
  startScaleFactor: 100
  finalScaleFactor: 0.2
  warmUpTime: 86400000
  maxBreaksPerMinute: 30
  erosionRatePerDay: 0
  destroyOnRemove: true
  blocksToErode: 1
  EnderPearls:
    preventEnderPearl: false
    #Town bastions don't prevent pearls.
    block_midair: false
    scaleFac: 1
    requireMaturity: true 
    consumeOnBlock: false  
